bindir := "bin/"
pname := "file-upload"

all: build

fmt:
  go fmt ./...

vet:
  go vet ./...

build: vet
  go build -o {{bindir}}{{pname}} ./cmd/server

serve: build
  ./{{bindir}}{{pname}}

check:
  staticcheck ./...

test:
  go test ./...

clean:
  rm -rf {{bindir}}
