// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notes.sql

package models

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNote = `-- name: CreateNote :one
INSERT INTO notes (workspace_id, author_id, title, content, tags)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, workspace_id, author_id, title, content, tags, created_at, updated_at
`

type CreateNoteParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	AuthorID    pgtype.Text `json:"author_id"`
	Title       string      `json:"title"`
	Content     string      `json:"content"`
	Tags        []string    `json:"tags"`
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, createNote,
		arg.WorkspaceID,
		arg.AuthorID,
		arg.Title,
		arg.Content,
		arg.Tags,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AuthorID,
		&i.Title,
		&i.Content,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNote = `-- name: DeleteNote :exec
DELETE FROM notes
WHERE workspace_id = $1 AND id = $2
`

type DeleteNoteParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) DeleteNote(ctx context.Context, arg DeleteNoteParams) error {
	_, err := q.db.Exec(ctx, deleteNote, arg.WorkspaceID, arg.ID)
	return err
}

const getWorkspaceNote = `-- name: GetWorkspaceNote :one
SELECT id, workspace_id, author_id, title, content, tags, created_at, updated_at FROM notes
WHERE workspace_id = $1 AND id = $2
`

type GetWorkspaceNoteParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) GetWorkspaceNote(ctx context.Context, arg GetWorkspaceNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, getWorkspaceNote, arg.WorkspaceID, arg.ID)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AuthorID,
		&i.Title,
		&i.Content,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWorkspaceNotes = `-- name: ListWorkspaceNotes :many
SELECT id, workspace_id, author_id, title, content, tags, created_at, updated_at FROM notes
WHERE workspace_id = $1
ORDER BY updated_at DESC
`

func (q *Queries) ListWorkspaceNotes(ctx context.Context, workspaceID pgtype.UUID) ([]Note, error) {
	rows, err := q.db.Query(ctx, listWorkspaceNotes, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Note
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.AuthorID,
			&i.Title,
			&i.Content,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNote = `-- name: UpdateNote :one
UPDATE notes
SET
  title = $3,
  content = $4,
  tags = $5,
  updated_at = NOW()
WHERE workspace_id = $1 AND id = $2
RETURNING id, workspace_id, author_id, title, content, tags, created_at, updated_at
`

type UpdateNoteParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ID          pgtype.UUID `json:"id"`
	Title       string      `json:"title"`
	Content     string      `json:"content"`
	Tags        []string    `json:"tags"`
}

func (q *Queries) UpdateNote(ctx context.Context, arg UpdateNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, updateNote,
		arg.WorkspaceID,
		arg.ID,
		arg.Title,
		arg.Content,
		arg.Tags,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AuthorID,
		&i.Title,
		&i.Content,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
