// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package models

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNewTask = `-- name: CreateNewTask :one
INSERT INTO tasks (
  workspace_id,
  title,
  description,
  assignee_id,
  status,
  priority,
  due_date
) VALUES (
  $1, -- workspace_id
  $2, -- title
  $3, -- description
  $4, -- assignee_id
  $5, -- status
  $6, -- priority
  $7  -- due_date
)
RETURNING id, workspace_id, title, description, assignee_id, status, priority, due_date, created_at, updated_at
`

type CreateNewTaskParams struct {
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	AssigneeID  pgtype.Text        `json:"assignee_id"`
	Status      TaskStatus         `json:"status"`
	Priority    NullTaskPriority   `json:"priority"`
	DueDate     pgtype.Timestamptz `json:"due_date"`
}

func (q *Queries) CreateNewTask(ctx context.Context, arg CreateNewTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createNewTask,
		arg.WorkspaceID,
		arg.Title,
		arg.Description,
		arg.AssigneeID,
		arg.Status,
		arg.Priority,
		arg.DueDate,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Title,
		&i.Description,
		&i.AssigneeID,
		&i.Status,
		&i.Priority,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks WHERE id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTask, id)
	return err
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT
    t.id AS task_id,
    t.workspace_id,
    t.title,
    t.description,
    t.status,
    t.priority,
    t.due_date,
    t.created_at,
    t.updated_at,

    -- Assignee info
    u.id AS assignee_id,
    u.first_name AS assignee_first_name,
    u.last_name AS assignee_last_name,
    u.username AS assignee_username,
    u.email AS assignee_email
FROM tasks t
LEFT JOIN users u ON t.assignee_id = u.id
WHERE t.id = $1
`

type GetTaskByIDRow struct {
	TaskID            pgtype.UUID        `json:"task_id"`
	WorkspaceID       pgtype.UUID        `json:"workspace_id"`
	Title             string             `json:"title"`
	Description       pgtype.Text        `json:"description"`
	Status            TaskStatus         `json:"status"`
	Priority          NullTaskPriority   `json:"priority"`
	DueDate           pgtype.Timestamptz `json:"due_date"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	AssigneeID        pgtype.Text        `json:"assignee_id"`
	AssigneeFirstName pgtype.Text        `json:"assignee_first_name"`
	AssigneeLastName  pgtype.Text        `json:"assignee_last_name"`
	AssigneeUsername  pgtype.Text        `json:"assignee_username"`
	AssigneeEmail     pgtype.Text        `json:"assignee_email"`
}

func (q *Queries) GetTaskByID(ctx context.Context, id pgtype.UUID) (GetTaskByIDRow, error) {
	row := q.db.QueryRow(ctx, getTaskByID, id)
	var i GetTaskByIDRow
	err := row.Scan(
		&i.TaskID,
		&i.WorkspaceID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AssigneeID,
		&i.AssigneeFirstName,
		&i.AssigneeLastName,
		&i.AssigneeUsername,
		&i.AssigneeEmail,
	)
	return i, err
}

const getTasksByWorkspace = `-- name: GetTasksByWorkspace :many
SELECT
    t.id AS task_id,
    t.workspace_id,
    t.title,
    t.description,
    t.status,
    t.priority,
    t.due_date,
    t.created_at,
    t.updated_at,

    -- Assignee info
    u.id AS assignee_id,
    u.first_name AS assignee_first_name,
    u.last_name AS assignee_last_name,
    u.username AS assignee_username,
    u.email AS assignee_email
FROM tasks t
LEFT JOIN users u ON t.assignee_id = u.id
WHERE t.workspace_id = $1
ORDER BY t.created_at DESC
`

type GetTasksByWorkspaceRow struct {
	TaskID            pgtype.UUID        `json:"task_id"`
	WorkspaceID       pgtype.UUID        `json:"workspace_id"`
	Title             string             `json:"title"`
	Description       pgtype.Text        `json:"description"`
	Status            TaskStatus         `json:"status"`
	Priority          NullTaskPriority   `json:"priority"`
	DueDate           pgtype.Timestamptz `json:"due_date"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	AssigneeID        pgtype.Text        `json:"assignee_id"`
	AssigneeFirstName pgtype.Text        `json:"assignee_first_name"`
	AssigneeLastName  pgtype.Text        `json:"assignee_last_name"`
	AssigneeUsername  pgtype.Text        `json:"assignee_username"`
	AssigneeEmail     pgtype.Text        `json:"assignee_email"`
}

func (q *Queries) GetTasksByWorkspace(ctx context.Context, workspaceID pgtype.UUID) ([]GetTasksByWorkspaceRow, error) {
	rows, err := q.db.Query(ctx, getTasksByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTasksByWorkspaceRow
	for rows.Next() {
		var i GetTasksByWorkspaceRow
		if err := rows.Scan(
			&i.TaskID,
			&i.WorkspaceID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AssigneeID,
			&i.AssigneeFirstName,
			&i.AssigneeLastName,
			&i.AssigneeUsername,
			&i.AssigneeEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET
  title = $2, -- title
  description = $3, -- description
  assignee_id = $4, -- assignee_id
  status = $5, -- status
  priority = $6, -- priority
  due_date = $7  -- due_date
WHERE id = $1
RETURNING id, workspace_id, title, description, assignee_id, status, priority, due_date, created_at, updated_at
`

type UpdateTaskParams struct {
	ID          pgtype.UUID        `json:"id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	AssigneeID  pgtype.Text        `json:"assignee_id"`
	Status      TaskStatus         `json:"status"`
	Priority    NullTaskPriority   `json:"priority"`
	DueDate     pgtype.Timestamptz `json:"due_date"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.AssigneeID,
		arg.Status,
		arg.Priority,
		arg.DueDate,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Title,
		&i.Description,
		&i.AssigneeID,
		&i.Status,
		&i.Priority,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
