bindir := "bin/"
pname := "workspace"

all: build

fmt:
  go fmt ./...

vet:
  go vet ./...

build: vet
  go build -o {{bindir}}{{pname}} ./cmd/server

serve: build
  ./{{bindir}}{{pname}}

check:
  staticcheck ./...

test:
  go test ./...

sql-fix:
  sqlfluff fix . --dialect postgres

sql-lint:
  sqlfluff lint . --dialect postgres

clean:
  rm -rf {{bindir}}